import { useFrame } from "@react-three/fiber";
import { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Table1 = ({ animate = true }) => {
    const { nodes, materials } = useGLTF("/sofa/table1.glb");
    const sofa = useRef();

    useFrame(({ clock }) => {
        if (animate) sofa.current.rotation.y = clock.getElapsedTime();
    });

    return (
        <group ref={sofa} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group position={[-0.1, 0.4, 0]} scale={1}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_6.geometry}
                            material={materials.qita}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_9.geometry}
                            material={materials.yizi}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_12.geometry}
                            material={materials.zhuozi}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_15.geometry}
                            material={materials.zhuozi}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_18.geometry}
                            material={materials.zhuozi}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_21.geometry}
                            material={materials.qita}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_24.geometry}
                            material={materials.qita}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_27.geometry}
                            material={materials.qita}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_30.geometry}
                            material={materials.yizi}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_33.geometry}
                            material={materials.yizi}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_36.geometry}
                            material={materials.yizi}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_39.geometry}
                            material={materials.yizi}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_42.geometry}
                            material={materials.yizi}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_45.geometry}
                            material={materials.boli}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_48.geometry}
                            material={materials.qita}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_51.geometry}
                            material={materials.qita}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_54.geometry}
                            material={materials.boli}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_57.geometry}
                            material={materials.qita}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_60.geometry}
                            material={materials.qita}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_63.geometry}
                            material={materials.qita}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_66.geometry}
                            material={materials.qita}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_69.geometry}
                            material={materials.boli}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_72.geometry}
                            material={materials.boli}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_75.geometry}
                            material={materials.qita}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_78.geometry}
                            material={materials.qita}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_81.geometry}
                            material={materials.qita}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_84.geometry}
                            material={materials.qita}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_87.geometry}
                            material={materials.qita}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_90.geometry}
                            material={materials.boli}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_93.geometry}
                            material={materials.qita}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_96.geometry}
                            material={materials.qita}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_99.geometry}
                            material={materials.qita}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_102.geometry}
                            material={materials.boli}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_105.geometry}
                            material={materials.qita}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_108.geometry}
                            material={materials.qita}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_111.geometry}
                            material={materials.yizi}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_114.geometry}
                            material={materials.yizi}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_117.geometry}
                            material={materials.yizi}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_120.geometry}
                            material={materials.yizi}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_123.geometry}
                            material={materials.yizi}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_126.geometry}
                            material={materials.yizi}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_129.geometry}
                            material={materials.yizi}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_132.geometry}
                            material={materials.boli}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_135.geometry}
                            material={materials.yeti}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_138.geometry}
                            material={materials.qita}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_141.geometry}
                            material={materials.qita}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_144.geometry}
                            material={materials.qita}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_147.geometry}
                            material={materials.qita}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_150.geometry}
                            material={materials.qita}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_153.geometry}
                            material={materials.boli}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_156.geometry}
                            material={materials.yeti}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_159.geometry}
                            material={materials.boli}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_162.geometry}
                            material={materials.yeti}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_165.geometry}
                            material={materials.boli}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_168.geometry}
                            material={materials.yeti}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_171.geometry}
                            material={materials.boli}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_174.geometry}
                            material={materials.yeti}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_177.geometry}
                            material={materials.boli}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_180.geometry}
                            material={materials.yeti}
                        />
                    </group>
                </group>
            </group>
        </group>
    );
};
useGLTF.preload("/sofa/table1.glb");

export default Table1;
